### ISSUE TITLE
Bad filename for dev-nodejs/form-data

### ISSUE THREAD

**Issue by kapsh** [zaufi/zaufi-overlay#2]
Paludis complains about `-rc3` in filename of dev-nodejs/form-data/form-data-1.0.0-rc3.ebuild

```
update-search-index>   ... When fetching versions of 'dev-nodejs/form-data' in zaufi-overlay:
update-search-index>   ... When loading versions for 'dev-nodejs/form-data' in zaufi-overlay:
update-search-index>   ... Skipping entry '/usr/portage/zaufi/dev-nodejs/form-data/form-data-1.0.0-rc3.ebuild' for 'dev-nodejs/form-data' in repository 'zaufi-overlay' due to exception 'Name '1.0.0-rc3' is not a valid version spec: unexpected trailing text 'c3'' (paludis::BadVersionSpecError)'
```

[File naming rules](https://devmanual.gentoo.org/ebuild-writing/file-format/index.html) agrees with that.

**Comment by zaufi** [comment]
Yeah, I know... all `dev-nodejs/*` ebuilds was generated automatically by very experimental script [npm2ebuild](https://github.com/zaufi/npm2ebuild) and it still far from good :( -- unfortunately I've faced w/ much more serious problem and still not found a right way to workaround, so now it is better to just remove all in that category…
